# Generated by Django 3.1.7 on 2021-03-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'user'), (2, 'moderator'), (1, 'admin')], null=True),
        ),
    ]
